# Generated by Django 3.2 on 2021-04-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_author_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Bloggers',
        ),
        migrations.RenameModel(
            old_name='Book',
            new_name='Blogs',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter a Blogs Genre', max_length=200),
        ),
    ]
