# Generated by Django 3.2 on 2021-04-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210422_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='image_url',
        ),
    ]
