# Generated by Django 3.2 on 2021-04-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_blogs_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='author',
            new_name='bloggers',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='genre',
        ),
        migrations.AddField(
            model_name='blogs',
            name='genre',
            field=models.ManyToManyField(help_text='Select a Genre for this Blogs', to='catalog.Genre'),
        ),
    ]
