# Generated by Django 3.2 on 2021-04-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210424_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloggers',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='genre',
        ),
        migrations.AddField(
            model_name='blogs',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this Blogs', to='catalog.Genre'),
        ),
    ]
