# Generated by Django 3.2 on 2021-04-25 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20210424_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='genre',
        ),
        migrations.AddField(
            model_name='blogs',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.genre'),
        ),
    ]
