# Generated by Django 3.2 on 2021-04-25 18:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0014_auto_20210425_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloggers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-post_date']},
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='post_data',
        ),
        migrations.AddField(
            model_name='blogs',
            name='post_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='summary',
            field=models.TextField(help_text='Enter you blog text here.', max_length=1000),
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Enter comment about blog here.', max_length=1000)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('bloggers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.blogs')),
            ],
            options={
                'ordering': ['post_date'],
            },
        ),
    ]
