# Generated by Django 3.2 on 2021-04-25 18:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0015_auto_20210425_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogComment',
            new_name='Comment',
        ),
    ]
