# Generated by Django 3.2 on 2021-04-25 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0016_rename_blogcomment_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloggers',
            options={'ordering': ['user', 'bio']},
        ),
        migrations.AddField(
            model_name='bloggers',
            name='bio',
            field=models.TextField(default=django.utils.timezone.now, help_text='Enter your bio details here.', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloggers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
