# Generated by Django 3.2 on 2021-04-27 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0018_auto_20210426_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloggers',
            options={'ordering': ['user', 'bio']},
        ),
        migrations.AddField(
            model_name='bloggers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
